// Example configuration file
// This file is generated by running: npm run setup
// DO NOT edit this manually - run setup instead

export const CONFIG = {
  storeName: 'your-store-name',
  authToken: 'Bearer eyJhbGci...', // Your full auth token
  apiBase: 'https://api.gorgias.work'
};
