import { ulid } from 'ulid';
import axios from 'axios';
import { readFileSync, existsSync } from 'fs';

// Try to load config from config.js (generated by setup.js)
let CONFIG;
try {
  const configModule = await import('./config.js');
  CONFIG = configModule.CONFIG;
  console.log('✓ Loaded configuration from config.js\n');
} catch (error) {
  console.error('Error: No configuration found!');
  console.error('Please run: npm run setup\n');
  process.exit(1);
}

/**
 * Generates all necessary IDs for an action configuration
 */
function generateIds() {
  return {
    configId: ulid(),
    internalId: ulid(),
    initialStepId: ulid(),
    successEndStepId: ulid(),
    errorEndStepId: ulid(),
    successTransitionId: ulid(),
    errorTransitionId: ulid()
  };
}

/**
 * Creates a complete action payload with generated IDs
 */
function createActionPayload(actionConfig, ids) {
  return {
    id: ids.configId,
    internal_id: ids.internalId,
    is_draft: false,
    name: actionConfig.name,
    advanced_datetime: new Date().toISOString(),
    initial_step_id: ids.initialStepId,
    available_languages: [],
    steps: [
      {
        id: ids.initialStepId,
        kind: 'http-request',
        settings: {
          name: actionConfig.requestName,
          url: actionConfig.url,
          method: actionConfig.method || 'GET',
          headers: actionConfig.headers || {},
          variables: actionConfig.variables || []
        }
      },
      {
        id: ids.successEndStepId,
        kind: 'end',
        settings: {
          success: true
        }
      },
      {
        id: ids.errorEndStepId,
        kind: 'end',
        settings: {
          success: false
        }
      }
    ],
    transitions: [
      {
        id: ids.successTransitionId,
        from_step_id: ids.initialStepId,
        to_step_id: ids.successEndStepId,
        name: 'Success',
        conditions: {
          and: [
            {
              equals: [
                { var: `steps_state.${ids.initialStepId}.success` },
                true
              ]
            }
          ]
        }
      },
      {
        id: ids.errorTransitionId,
        from_step_id: ids.initialStepId,
        to_step_id: ids.errorEndStepId,
        name: 'Error'
      }
    ],
    apps: [],
    triggers: [
      {
        kind: 'llm-prompt',
        settings: {
          custom_inputs: [],
          object_inputs: [],
          conditions: null,
          outputs: []
        }
      }
    ],
    entrypoints: [
      {
        kind: 'llm-conversation',
        trigger: 'llm-prompt',
        settings: {
          requires_confirmation: actionConfig.requiresConfirmation || false,
          instructions: actionConfig.description
        },
        deactivated_datetime: null
      }
    ]
  };
}

/**
 * Creates an action via PUT request to Gorgias API
 */
async function createAction(actionConfig) {
  const ids = generateIds();
  const payload = createActionPayload(actionConfig, ids);

  const url = `${CONFIG.apiBase}/stores/shopify/${CONFIG.storeName}/configurations/${ids.internalId}`;

  console.log(`\nCreating action: ${actionConfig.name}`);
  console.log(`URL: ${url}`);

  try {
    const response = await axios.put(url, payload, {
      headers: {
        'Authorization': `Bearer ${CONFIG.authToken}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      }
    });

    console.log(`✓ Success! Action created with ID: ${ids.configId}`);
    return { success: true, id: ids.configId, data: response.data };
  } catch (error) {
    console.error(`✗ Failed to create action: ${actionConfig.name}`);
    if (error.response) {
      console.error(`  Status: ${error.response.status}`);
      console.error(`  Error: ${JSON.stringify(error.response.data, null, 2)}`);
    } else {
      console.error(`  Error: ${error.message}`);
    }
    return { success: false, error: error.message };
  }
}

/**
 * Bulk create actions from a configuration file
 */
async function bulkCreateActions(actionsFile = './actions-config.json') {
  console.log('Starting bulk action creation...\n');

  let actionsConfig;
  try {
    actionsConfig = JSON.parse(readFileSync(actionsFile, 'utf8'));
  } catch (error) {
    console.error(`Failed to read actions config file: ${actionsFile}`);
    console.error(error.message);
    process.exit(1);
  }

  const results = [];

  for (const action of actionsConfig.actions) {
    const result = await createAction(action);
    results.push(result);

    // Add a small delay between requests to be nice to the API
    await new Promise(resolve => setTimeout(resolve, 500));
  }

  // Summary
  console.log('\n' + '='.repeat(50));
  console.log('SUMMARY');
  console.log('='.repeat(50));
  const successful = results.filter(r => r.success).length;
  const failed = results.filter(r => !r.success).length;
  console.log(`Total: ${results.length}`);
  console.log(`Successful: ${successful}`);
  console.log(`Failed: ${failed}`);
}

// Run if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  const configFile = process.argv[2] || './actions-config.json';
  bulkCreateActions(configFile).catch(console.error);
}

export { createAction, generateIds, createActionPayload };
